/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/tomatodx/admin`; params?: Router.UnknownInputParams; } | { pathname: `/tomatodx/capture`; params?: Router.UnknownInputParams; } | { pathname: `/tomatodx/history`; params?: Router.UnknownInputParams; } | { pathname: `/tomatodx`; params?: Router.UnknownInputParams; } | { pathname: `/tomatodx/preview`; params?: Router.UnknownInputParams; } | { pathname: `/tomatodx/result`; params?: Router.UnknownInputParams; } | { pathname: `/tomatodx/settings`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/tomatodx/admin`; params?: Router.UnknownOutputParams; } | { pathname: `/tomatodx/capture`; params?: Router.UnknownOutputParams; } | { pathname: `/tomatodx/history`; params?: Router.UnknownOutputParams; } | { pathname: `/tomatodx`; params?: Router.UnknownOutputParams; } | { pathname: `/tomatodx/preview`; params?: Router.UnknownOutputParams; } | { pathname: `/tomatodx/result`; params?: Router.UnknownOutputParams; } | { pathname: `/tomatodx/settings`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/tomatodx/admin${`?${string}` | `#${string}` | ''}` | `/tomatodx/capture${`?${string}` | `#${string}` | ''}` | `/tomatodx/history${`?${string}` | `#${string}` | ''}` | `/tomatodx${`?${string}` | `#${string}` | ''}` | `/tomatodx/preview${`?${string}` | `#${string}` | ''}` | `/tomatodx/result${`?${string}` | `#${string}` | ''}` | `/tomatodx/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/tomatodx/admin`; params?: Router.UnknownInputParams; } | { pathname: `/tomatodx/capture`; params?: Router.UnknownInputParams; } | { pathname: `/tomatodx/history`; params?: Router.UnknownInputParams; } | { pathname: `/tomatodx`; params?: Router.UnknownInputParams; } | { pathname: `/tomatodx/preview`; params?: Router.UnknownInputParams; } | { pathname: `/tomatodx/result`; params?: Router.UnknownInputParams; } | { pathname: `/tomatodx/settings`; params?: Router.UnknownInputParams; };
    }
  }
}
