/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/tomatodx/history`; params?: Router.UnknownInputParams; } | { pathname: `/tomatodx`; params?: Router.UnknownInputParams; } | { pathname: `/tomatodx/preview`; params?: Router.UnknownInputParams; } | { pathname: `/tomatodx/profile`; params?: Router.UnknownInputParams; } | { pathname: `/tomatodx/result`; params?: Router.UnknownInputParams; } | { pathname: `/tomatodx/scan`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/tomatodx/history`; params?: Router.UnknownOutputParams; } | { pathname: `/tomatodx`; params?: Router.UnknownOutputParams; } | { pathname: `/tomatodx/preview`; params?: Router.UnknownOutputParams; } | { pathname: `/tomatodx/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/tomatodx/result`; params?: Router.UnknownOutputParams; } | { pathname: `/tomatodx/scan`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/tomatodx/history${`?${string}` | `#${string}` | ''}` | `/tomatodx${`?${string}` | `#${string}` | ''}` | `/tomatodx/preview${`?${string}` | `#${string}` | ''}` | `/tomatodx/profile${`?${string}` | `#${string}` | ''}` | `/tomatodx/result${`?${string}` | `#${string}` | ''}` | `/tomatodx/scan${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/tomatodx/history`; params?: Router.UnknownInputParams; } | { pathname: `/tomatodx`; params?: Router.UnknownInputParams; } | { pathname: `/tomatodx/preview`; params?: Router.UnknownInputParams; } | { pathname: `/tomatodx/profile`; params?: Router.UnknownInputParams; } | { pathname: `/tomatodx/result`; params?: Router.UnknownInputParams; } | { pathname: `/tomatodx/scan`; params?: Router.UnknownInputParams; };
    }
  }
}
